"""empty message

Revision ID: 55996b2e583d
Revises: 
Create Date: 2023-02-25 12:57:07.523701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55996b2e583d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'username', 'password', name='user_pkey')
    )
    # ### end Alembic commands ###
