"""empty message

Revision ID: 681a0a4e0d3e
Revises: 40ccc3c723b8
Create Date: 2023-02-25 15:28:08.094813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681a0a4e0d3e'
down_revision = '40ccc3c723b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srcIp', sa.String(length=80), nullable=True),
    sa.Column('dstIp', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic')
    # ### end Alembic commands ###
