"""empty message

Revision ID: e1553096ad76
Revises: 546eb6a5a887
Create Date: 2023-02-25 13:03:04.974709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1553096ad76'
down_revision = '546eb6a5a887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updatedAt')
    op.drop_column('user', 'createdAt')
    # ### end Alembic commands ###
